language: ruby
rvm:
- 2.2.2
deploy:
  provider: heroku
  api_key:
    secure: P2XOtuygGYkFbdN4v8Mo3FeqIFPcoBiAC9IBmPOzwIIaipW27zLtjbSnFdBr9KxTcSjro4+ngDhcKgWMy12UdRgKxz0OJ11oVoQ6VUqZLtMeswzIW/W09vDlUiDfdyPVatR9+onjFoqeW7PSKhCH/uf9Aal+oLY4msihOQFoutEHaP4vcw9w1vIYE7igzTHFaFpGMcwbG1uIUMvTNb+KclRr2kDsxevy7FeDnFUNA5/Kli2VMksHRq2LUiUVkl0H8jNYFb3KIEupvNYjKCghhZX/hzvKO7crRi5nmtvfvF0o3MaDoqYe2O8LA8ZMsvhCs81HjnTSboIpnYCPNxkxGZup+EZFkY3aPbLrJ9shD4ORJu48nZll39FJgdgo90YCrPjoda4JFKNy97iVoflpPmGfqnYvqQiWW/7LaIFY3MWIBMb2b9hrm6o+wdqWdRBnqg2MjkXOfdQWpfbUGu2yWsZyPqqbPh9Rwr1adZ6ujs9uAupSTcHKBTFuW7EU9dKJwd+a08x77Z4ubhr5HIz7UQiZQ9gkZnLJtMZcDVEGeMEDTO/ZWRXcPQMKfxvM7qooYyB1+MjpnR/f7veVfZjZh7PtVA+epoL+6ETt8Dr0I1vb8yF3OGmDklzQ7+/qrdTKi7Vr5Hc3/Q+KSZ56WGVYyLZ3IOL0BN9Xd5rx5s8VjNo=
  app: intense-beyond-5963
  on:
    repo: hyoshiok/r_ranking
